### ISSUE TITLE
Visual Studio 2017 build

### ISSUE THREAD

**Issue by amedina1570** [AmorBielyi/qiskit-simulator-win-mvs#1]
Running the program doesn't show up any output. Do I have to pass any arguments on VS?

**Comment by AmorBielyi** [comment]
Hi, Arnaldy Medina.
- You can open file in simulator with command line, just add argument, in example: "**YOUR_PATH_TO_SIMULATOR**/qiskit-simulator-win-mvs.exe **YOUR_FILE_**.json"
- if you want open file programmatically, change code in **main.cpp**, as an option do this:
add string variable which contains **your file path/file name**.
 **line >=53**, replace argc ==2 to true.
 **line >=56**, replace std::string(argv[1]) to your var.
- or just simply drag&drop file into application.
